### ISSUE TITLE
Cannot migrate database

### ISSUE THREAD

**Issue by aazpeitia** [ELDAELRA/ELRI#5]
We get a `django.db.migrations.state.InvalidBasesError` error at database migration time. This error happens using a python virtual environment and with the local python installation. The error trace is the following:

```
python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: stats, project_management, repository, bcp47, storage, sitemaps, accounts, recommendations, analytical, selectable, haystack
  Apply all migrations: sessions, admin, tastypie, auth, sites, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Creating table accounts_registrationrequest
    Creating table accounts_resetrequest
    Creating table accounts_accesspointedeliveryapplication
    Creating table accounts_editorgroup
    Creating table accounts_editorgroupapplication
    Creating table accounts_editorgroupmanagers
    Creating table accounts_organization
    Creating table accounts_organizationapplication
    Creating table accounts_organizationmanagers
    Creating table accounts_userprofile_default_editor_groups
    Creating table accounts_userprofile
    Creating table storage_storageobject
    Creating table stats_lrstats
    Creating table stats_querystats
    Creating table stats_usagestats
    Creating table recommendations_togethermanager
    Creating table recommendations_resourcecountdict
    Creating table recommendations_resourcecountpair
    Creating table repository_resourceinfotype_model_editor_groups
    Creating table repository_resourceinfotype_model_contactPerson
    Creating table repository_resourceinfotype_model_owners
    Creating table repository_resourceinfotype_model
    Creating table repository_sizeinfotype_model
    Creating table repository_identificationinfotype_model
    Creating table repository_versioninfotype_model
    Creating table repository_validationinfotype_model_validator
    Creating table repository_validationinfotype_model_validationReport
    Creating table repository_validationinfotype_model
    Creating table repository_resourcecreationinfotype_model_fundingProject
    Creating table repository_resourcecreationinfotype_model_resourceCreator
    Creating table repository_resourcecreationinfotype_model
    Creating table repository_creationinfotype_model_originalSource
    Creating table repository_creationinfotype_model_creationTool
    Creating table repository_creationinfotype_model
    Creating table repository_metadatainfotype_model_metadataCreator
    Creating table repository_metadatainfotype_model
    Creating table repository_documentationinfotype_model
    Creating table repository_documentinfotype_model
    Creating table repository_resourcedocumentationinfotype_model_documentation
    Creating table repository_resourcedocumentationinfotype_model
    Creating table repository_domaininfotype_model
    Creating table repository_annotationinfotype_model_annotationManual
    Creating table repository_annotationinfotype_model_annotationTool
    Creating table repository_annotationinfotype_model
    Creating table repository_targetresourceinfotype_model
    Creating table repository_relationinfotype_model
    Creating table repository_dependenciesinfotype_model_requiredLRs
    Creating table repository_dependenciesinfotype_model_requiredSoftware
    Creating table repository_dependenciesinfotype_model
    Creating table repository_communicationinfotype_model
    Creating table repository_actorinfotype_model
    Creating table repository_organizationinfotype_model
    Creating table repository_personinfotype_model_affiliation
    Creating table repository_personinfotype_model
    Creating table repository_distributioninfotype_model_licenceInfo
    Creating table repository_distributioninfotype_model_iprHolder
    Creating table repository_distributioninfotype_model
    Creating table repository_licenceinfotype_model
    Creating table repository_characterencodinginfotype_model
    Creating table repository_lingualityinfotype_model
    Creating table repository_languagevarietyinfotype_model
    Creating table repository_languageinfotype_model_sizePerLanguage
    Creating table repository_languageinfotype_model_languageVarietyInfo
    Creating table repository_languageinfotype_model
    Creating table repository_languagesetinfotype_model
    Creating table repository_projectinfotype_model
    Creating table repository_corpustextinfotype_model
    Creating table repository_textformatinfotype_model
    Creating table repository_textclassificationinfotype_model
    Creating table repository_languagedescriptionencodinginfotype_model
    Creating table repository_languagedescriptiontextinfotype_model
    Creating table repository_lexicalconceptualresourceencodinginfotype_model
    Creating table repository_lexicalconceptualresourcetextinfotype_model
    Creating table repository_inputinfotype_model_domainSetInfo
    Creating table repository_inputinfotype_model
    Creating table repository_outputinfotype_model
    Creating table repository_toolserviceevaluationinfotype_model_evaluator
    Creating table repository_toolserviceevaluationinfotype_model_evaluationReport
    Creating table repository_toolserviceevaluationinfotype_model_evaluationTool
    Creating table repository_toolserviceevaluationinfotype_model
    Creating table repository_toolserviceoperationinfotype_model
    Creating table repository_toolservicecreationinfotype_model_originalSource
    Creating table repository_toolservicecreationinfotype_model
    Creating table repository_resourcecomponenttypetype_model
    Creating table repository_lexicalconceptualresourceinfotype_model
    Creating table repository_languagedescriptioninfotype_model
    Creating table repository_toolserviceinfotype_model
    Creating table repository_corpusinfotype_model
    Creating table repository_corpusmediatypetype_model
    Creating table repository_languagedescriptionmediatypetype_model
    Creating table repository_lexicalconceptualresourcemediatypetype_model
    Creating table repository_domainsetinfotype_model
    Creating table repository_documentunstructuredstring_model
    Creating table project_management_managementobject
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'accounts.EditorGroup'>, <ModelState: 'accounts.EditorGroupManagers'>, <ModelState: 'accounts.Organization'>, <ModelState: 'accounts.OrganizationManagers'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
```

**Comment by popescuv** [comment]
The proper manipulation is to generate the migrations on the deployment site:
python manage.py makemigrations accounts repository stats recommendations storage
