### ISSUE TITLE
Django docker image - Adding alternative to the development mode startup (runserver)

### ISSUE THREAD

**Issue by jcorteslinkare** [ELDAELRA/ELRI#61]
After adding gunicorn and futures to requirements.txt, i am trying to startup the django image with the command:

"gunicorn metashare.wsgi -b 0.0.0.0:8000 -w 4 --threads 8 --preload"

Even after changing wsgi.py file to os.environ['DJANGO_SETTINGS_MODULE'] = 'metashare.settings' i am getting the error :

```
elri_app           | Traceback (most recent call last):
elri_app           |   File "/usr/local/bin/gunicorn", line 10, in <module>
elri_app           |     sys.exit(run())
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
elri_app           |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 223, in run
elri_app           |     super(Application, self).run()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
elri_app           |     Arbiter(self).run()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 60, in __init__
elri_app           |     self.setup(app)
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 120, in setup
elri_app           |     self.app.wsgi()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
elri_app           |     self.callable = self.load()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
elri_app           |     return self.load_wsgiapp()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
elri_app           |     return util.import_app(self.app_uri)
elri_app           |   File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
elri_app           |     __import__(module)
elri_app           |   File "/elri/metashare/wsgi.py", line 5, in <module>
elri_app           |     application = get_wsgi_application()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
elri_app           |     django.setup()
elri_app           |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 20, in setup
elri_app           |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
elri_app           |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
elri_app           |     self._setup(name)
elri_app           |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
elri_app           |     self._wrapped = Settings(settings_module)
elri_app           |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
elri_app           |     % (self.SETTINGS_MODULE, e)
elri_app           | ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named settings
elri_app           | 2019/01/28 11:31:36 Command exited with error: exit status 1
```

**Comment by emartinezvic** [comment]
Have you checked if ELRI/metashare is in the sys.path? 
[Here](https://stackoverflow.com/questions/12987648/importerror-could-not-import-settings)  they suggest to add the following in the wsi.py file : 
 `sys.path.append(' PATH_TO_METASHARE_FOLDER/metashare')`
Then, it seems that the os.environ['DJANGO_SETTINGS_MODULE'] = 'metashare.settings' should make the app find the metashare/settings.py file
Hope this can help :)

**Comment by jcorteslinkare** [comment]
Hi Eva,

It was my bad all along... I updated wsgi.py wrong location, first correction worked flawlessly:

```
import os
from django.core.wsgi import get_wsgi_application

os.environ['DJANGO_SETTINGS_MODULE'] = 'metashare.settings'
application = get_wsgi_application()
```

**Comment by jcorteslinkare** [comment]
Commited changes, will be available as soon as we push the new images to docker hub

**Comment by jcorteslinkare** [comment]
Also added a new shared volume (between django and nginx image) so that static images can be served by NGINX when gunicorn is being used:

  elri-node1:
    volumes:
      - elri-static-resources:/elri/static:rw
  nginx:
    volumes:
      - elri-static-resources:/www/data/static:ro

volumes:
  elri-static-resources:
    name: elri-static
